logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.bcnc.techtest: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:techtest
    driverClassName: org.h2.Driver
    username: ${techtest.user}
    password: ${techtest.pass}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
springdoc:
  api-docs:
    enabled: true
    path: /api/docs