logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    com.example.techtest: DEBUG
spring:
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:techtest
    username: ${techtest.user}
    password: ${techtest.pass}
  jpa:
    repositories:
      enabled: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
springdoc:
  api-docs:
    enabled: true
    path: /api/docs
server:
  servlet:
    context-path: /example/techtest